<?php

namespace AppBundle\Repository;

/**
 * AccountMovementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountMovementRepository extends \Doctrine\ORM\EntityRepository
{
}
