<?php

namespace AppBundle\Repository;

/**
 * BudgetItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetItemRepository extends \Doctrine\ORM\EntityRepository
{
}
