<?php

namespace AppBundle\Repository;

/**
 * BudgetItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByBudgetId($value)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT i FROM AppBundle:BudgetItem i where i.budget = :value"
            )
            ->setParameter('value', $value)
            ->getResult();
    }
}
