<?php

namespace AppBundle\Repository;

/**
 * BudgetStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetStateRepository extends \Doctrine\ORM\EntityRepository
{
}
