<?php

namespace AppBundle\Repository;

/**
 * CreditNoteItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreditNoteItemRepository extends \Doctrine\ORM\EntityRepository
{
}
