<?php

namespace AppBundle\Repository;

/**
 * CreditNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreditNoteRepository extends \Doctrine\ORM\EntityRepository
{
}
