<?php

namespace AppBundle\Repository;

/**
 * DebitNoteAccountMovementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DebitNoteAccountMovementRepository extends \Doctrine\ORM\EntityRepository
{
}
