<?php

namespace AppBundle\Repository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByAttribute($attribute, $alias, $value)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT c.id, c.$attribute as $alias FROM AppBundle:Customer c where c.$attribute like :value order by c.name asc"
            )
            ->setParameter('value', '%' . $value . '%')
            ->getResult();
    }
}
