<?php

namespace AppBundle\Repository;

/**
 * DebitNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DebitNoteRepository extends \Doctrine\ORM\EntityRepository
{
}
