<?php

namespace AppBundle\Repository;

/**
 * InvoiceAccountMovementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceAccountMovementRepository extends \Doctrine\ORM\EntityRepository
{
}
