<?php

namespace AppBundle\Repository;

/**
 * OrderItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByOrderId($value)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT i FROM AppBundle:OrderItem i where i.order = :value"
            )
            ->setParameter('value', $value)
            ->getResult();
    }
}
