<?php

namespace AppBundle\Repository;

/**
 * OrderCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
