<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByAttribute($attribute, $value)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p.code, p.name, p.price FROM AppBundle:Product p where p.$attribute = :value"
            )
            ->setParameter('value', $value)
            ->getResult();
    }
}
