<?php

namespace AppBundle\Repository;

/**
 * SalesConditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesConditionRepository extends \Doctrine\ORM\EntityRepository
{
}
