<?php

namespace AppBundle\Repository;

/**
 * SalesPointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesPointRepository extends \Doctrine\ORM\EntityRepository
{
}
