# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.datatable.user:
        class: AppBundle\Datatables\UserDatatable
        parent: sg_datatables.datatable.abstract
    
    app.datatable.customer:
        class: AppBundle\Datatables\CustomerDatatable
        parent: sg_datatables.datatable.abstract
        
    app.datatable.ivacondition:
        class: AppBundle\Datatables\IvaConditionDatatable
        parent: sg_datatables.datatable.abstract
        
    app.datatable.category:
        class: AppBundle\Datatables\CategoryDatatable
        parent: sg_datatables.datatable.abstract
    
    app.datatable.provider:
        class: AppBundle\Datatables\ProviderDatatable
        parent: sg_datatables.datatable.abstract
    
    app.datatable.product:
        class: AppBundle\Datatables\ProductDatatable
        parent: sg_datatables.datatable.abstract
        
    app.datatable.purchaseorder:
        class: AppBundle\Datatables\PurchaseOrderDatatable
        parent: sg_datatables.datatable.abstract
        
    app.datatable.orderstate:
        class: AppBundle\Datatables\OrderStateDatatable
        parent: sg_datatables.datatable.abstract
        
    app.datatable.salespoint:
        class: AppBundle\Datatables\SalesPointDatatable
        parent: sg_datatables.datatable.abstract
      
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
